### ISSUE TITLE
Error playing media from source files

### ISSUE THREAD

**Issue by TDLabs2015** [thisismy-github/pyplayer#6]
Hi, trying to install the source files and am met with this error immedietly when scrolling the timeline OR letting it play for 3 seconds etc.. then the player shuts down, did manage to test the exe version and that seems to work fine at least for playing videos.. would really like to check this work out so your response is very appreiciated. cheers

[000001de28e95c10] avcodec decoder: Using D3D11VA (NVIDIA GeForce RTX 3080 Ti, vendor 10de(NVIDIA), device 2208, revision a1) for hardware decoding
Traceback (most recent call last):
  File "b:\0 - TDLabs\0 - Other\pyplayer-master\widgets.py", line 1124, in paintEvent
    pos.setY(self.height() - (self.height() - size) / 2)
TypeError: setY(self, ypos: int): argument 1 has unexpected type 'float'

**Comment by thisismy-github** [comment]
What version of Python did you compile with? I was compiling with 3.9.12 and I do actually get a deprecation warning there: 
`DeprecationWarning: an integer is required (got type float). Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.`

Maybe they finally removed it. I'll try to track down these kinds of errors when I resume working on this (in a few weeks hopefully),  but for now you should try compiling with a lower Python version if it's not too much hassle.
